[build]
  base = "frontend"
  publish = "frontend/out"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://sagarbpatel31.pythonanywhere.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://sagarbpatel31.pythonanywhere.com"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://sagarbpatel31.pythonanywhere.com"